# Generated by Django 3.2.6 on 2021-08-18 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_image_model_imageupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='image_model',
            name='image_Type',
            field=models.CharField(blank=True, choices=[('Free', 'Free'), ('Paid', 'Paid')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='image_model',
            name='image_Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.image_cat'),
        ),
    ]
