# Generated by Django 3.2.6 on 2021-08-18 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_image_model_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_model',
            name='imageData',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Your image raw'),
        ),
        migrations.AddField(
            model_name='image_model',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image_model',
            name='imageTitle',
            field=models.CharField(max_length=25, verbose_name='Image Title'),
        ),
        migrations.AlterField(
            model_name='image_model',
            name='imageUpload',
            field=models.ImageField(upload_to='Image_upload/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='image_model',
            name='image_Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.image_cat', verbose_name='Categoty'),
        ),
        migrations.AlterField(
            model_name='image_model',
            name='image_Type',
            field=models.CharField(blank=True, choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Free', max_length=5, null=True, verbose_name='Image Type'),
        ),
    ]
