# Generated by Django 3.2.6 on 2021-08-18 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210818_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_model',
            old_name='user',
            new_name='owner',
        ),
    ]
