# Generated by Django 3.2.6 on 2021-08-18 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_rename_user_image_model_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_model',
            name='owner',
            field=models.ForeignKey(blank=True, default='User', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
